package codexremote

import (
	"fmt"
	"io"
)

func PrintAgentHandoff(w io.Writer, title, websocketURL, token string) {
	fmt.Fprintln(w)
	fmt.Fprintln(w, "============================================================")
	fmt.Fprintln(w, title)
	fmt.Fprintln(w, "Copy this block into another agent:")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "BEGIN_AGENT_HANDOFF")
	fmt.Fprintln(w, "You can interact with a remote Codex app-server over WebSocket.")
	fmt.Fprintln(w, "Use the values below exactly.")
	fmt.Fprintln(w, "The original `codex-remote` process must stay running while you use this endpoint.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "CODEX_REMOTE_URL="+websocketURL)
	fmt.Fprintln(w, "CODEX_REMOTE_TOKEN="+token)
	fmt.Fprintln(w, "AUTH_HEADER=Authorization: Bearer <CODEX_REMOTE_TOKEN>")
	fmt.Fprintln(w, "PROTOCOL=codex-app-server-websocket")
	fmt.Fprintln(w, "FIRST_REQUEST=initialize")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Shell exports:")
	fmt.Fprintln(w, "export CODEX_REMOTE_URL='"+websocketURL+"'")
	fmt.Fprintln(w, "export CODEX_REMOTE_TOKEN='"+token+"'")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Minimal Python client:")
	fmt.Fprintln(w, `python3 - <<'PY'`)
	fmt.Fprintln(w, `import os, asyncio, json, websockets`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `async def main():`)
	fmt.Fprintln(w, `    async with websockets.connect(`)
	fmt.Fprintln(w, `        os.environ["CODEX_REMOTE_URL"],`)
	fmt.Fprintln(w, `        additional_headers={"Authorization": f"Bearer {os.environ['CODEX_REMOTE_TOKEN']}"} ) as ws:`)
	fmt.Fprintln(w, `        await ws.send(json.dumps({`)
	fmt.Fprintln(w, `            "id": 1,`)
	fmt.Fprintln(w, `            "method": "initialize",`)
	fmt.Fprintln(w, `            "params": {"clientInfo": {"name": "remote-agent", "version": "0.1.0"}, "capabilities": {"experimentalApi": True}},`)
	fmt.Fprintln(w, `        }))`)
	fmt.Fprintln(w, `        print(await ws.recv())`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `asyncio.run(main())`)
	fmt.Fprintln(w, `PY`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "After initialize, continue with thread/start and turn/start.")
	fmt.Fprintln(w, "END_AGENT_HANDOFF")
	fmt.Fprintln(w, "============================================================")
	fmt.Fprintln(w)
}

func PrintHTTPAgentHandoff(w io.Writer, title, baseURL, token, defaultCWD string) {
	fmt.Fprintln(w)
	fmt.Fprintln(w, "============================================================")
	fmt.Fprintln(w, title)
	fmt.Fprintln(w, "Copy this block into another agent:")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "BEGIN_HTTP_AGENT_HANDOFF")
	fmt.Fprintln(w, "You can interact with this Codex host over plain HTTP.")
	fmt.Fprintln(w, "Use the values below exactly.")
	fmt.Fprintln(w, "The original `codex-remote` process must stay running while you use this endpoint.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "CODEX_REMOTE_HTTP_URL="+baseURL)
	fmt.Fprintln(w, "CODEX_REMOTE_TOKEN="+token)
	fmt.Fprintln(w, "AUTH_HEADER=Authorization: Bearer <CODEX_REMOTE_TOKEN>")
	fmt.Fprintln(w, "CREATE_THREAD_ENDPOINT=POST /v1/threads")
	fmt.Fprintln(w, "RESUME_THREAD_ENDPOINT=POST /v1/threads/{thread_id}/turns")
	fmt.Fprintln(w, "READY_ENDPOINT=GET /readyz")
	if defaultCWD != "" {
		fmt.Fprintln(w, "DEFAULT_CWD="+defaultCWD)
	}
	fmt.Fprintln(w, "DEFAULT_SANDBOX=workspace-write")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Shell exports:")
	fmt.Fprintln(w, "export CODEX_REMOTE_HTTP_URL='"+baseURL+"'")
	fmt.Fprintln(w, "export CODEX_REMOTE_TOKEN='"+token+"'")
	if defaultCWD != "" {
		fmt.Fprintln(w, "export CODEX_REMOTE_DEFAULT_CWD='"+defaultCWD+"'")
	}
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Create a new thread:")
	fmt.Fprintln(w, `curl -sS "$CODEX_REMOTE_HTTP_URL/v1/threads" \`)
	fmt.Fprintln(w, `  -H "Authorization: Bearer $CODEX_REMOTE_TOKEN" \`)
	fmt.Fprintln(w, `  -H "Content-Type: application/json" \`)
	fmt.Fprintln(w, `  -d '{"prompt":"Reply with exactly: OK","cwd":"'"$CODEX_REMOTE_DEFAULT_CWD"'"}'`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Minimal Python client:")
	fmt.Fprintln(w, `python3 - <<'PY'`)
	fmt.Fprintln(w, `import json, os, urllib.request`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `base = os.environ["CODEX_REMOTE_HTTP_URL"]`)
	fmt.Fprintln(w, `token = os.environ["CODEX_REMOTE_TOKEN"]`)
	fmt.Fprintln(w, `cwd = os.environ.get("CODEX_REMOTE_DEFAULT_CWD", "")`)
	fmt.Fprintln(w, `payload = {"prompt": "Reply with exactly: OK"}`)
	fmt.Fprintln(w, `if cwd: payload["cwd"] = cwd`)
	fmt.Fprintln(w, `req = urllib.request.Request(`)
	fmt.Fprintln(w, `    base + "/v1/threads",`)
	fmt.Fprintln(w, `    data=json.dumps(payload).encode(),`)
	fmt.Fprintln(w, `    headers={`)
	fmt.Fprintln(w, `        "Authorization": f"Bearer {token}",`)
	fmt.Fprintln(w, `        "Content-Type": "application/json",`)
	fmt.Fprintln(w, `    },`)
	fmt.Fprintln(w, `    method="POST",`)
	fmt.Fprintln(w, `)`)
	fmt.Fprintln(w, `with urllib.request.urlopen(req) as resp:`)
	fmt.Fprintln(w, `    print(resp.read().decode())`)
	fmt.Fprintln(w, `PY`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "END_HTTP_AGENT_HANDOFF")
	fmt.Fprintln(w, "============================================================")
	fmt.Fprintln(w)
}
