package codexremote

import (
	"fmt"
	"io"
)

func PrintAgentHandoff(w io.Writer, title, websocketURL, token string) {
	fmt.Fprintln(w)
	fmt.Fprintln(w, "============================================================")
	fmt.Fprintln(w, title)
	fmt.Fprintln(w, "Copy this block into another agent:")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "BEGIN_AGENT_HANDOFF")
	fmt.Fprintln(w, "You can interact with a remote Codex app-server over WebSocket.")
	fmt.Fprintln(w, "Use the values below exactly.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "CODEX_REMOTE_URL="+websocketURL)
	fmt.Fprintln(w, "CODEX_REMOTE_TOKEN="+token)
	fmt.Fprintln(w, "AUTH_HEADER=Authorization: Bearer <CODEX_REMOTE_TOKEN>")
	fmt.Fprintln(w, "PROTOCOL=codex-app-server-websocket")
	fmt.Fprintln(w, "FIRST_REQUEST=initialize")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Shell exports:")
	fmt.Fprintln(w, "export CODEX_REMOTE_URL='"+websocketURL+"'")
	fmt.Fprintln(w, "export CODEX_REMOTE_TOKEN='"+token+"'")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Minimal Python client:")
	fmt.Fprintln(w, `python3 - <<'PY'`)
	fmt.Fprintln(w, `import os, asyncio, json, websockets`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `async def main():`)
	fmt.Fprintln(w, `    async with websockets.connect(`)
	fmt.Fprintln(w, `        os.environ["CODEX_REMOTE_URL"],`)
	fmt.Fprintln(w, `        additional_headers={"Authorization": f"Bearer {os.environ['CODEX_REMOTE_TOKEN']}"} ) as ws:`)
	fmt.Fprintln(w, `        await ws.send(json.dumps({`)
	fmt.Fprintln(w, `            "id": 1,`)
	fmt.Fprintln(w, `            "method": "initialize",`)
	fmt.Fprintln(w, `            "params": {"clientInfo": {"name": "remote-agent", "version": "0.1.0"}, "capabilities": {"experimentalApi": True}},`)
	fmt.Fprintln(w, `        }))`)
	fmt.Fprintln(w, `        print(await ws.recv())`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `asyncio.run(main())`)
	fmt.Fprintln(w, `PY`)
	fmt.Fprintln(w)
	fmt.Fprintln(w, "After initialize, continue with thread/start and turn/start.")
	fmt.Fprintln(w, "END_AGENT_HANDOFF")
	fmt.Fprintln(w, "============================================================")
	fmt.Fprintln(w)
}
